{"text": "2023-12-18 12:43:50 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.969385", "seconds": 1.969385}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 5365, "name": "MainProcess"}, "thread": {"id": 139644727856000, "name": "MainThread"}, "time": {"repr": "2023-12-18 12:43:50.017254+08:00", "timestamp": 1702874630.017254}}}
{"text": "2023-12-18 12:44:00 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Destiny 2: Legacy Collection', 'url': 'https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023'}\n", "record": {"elapsed": {"repr": "0:00:12.607348", "seconds": 12.607348}, "exception": null, "extra": {"title": "Destiny 2: Legacy Collection", "url": "https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023"}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 5365, "name": "MainProcess"}, "thread": {"id": 139644727856000, "name": "MainThread"}, "time": {"repr": "2023-12-18 12:44:00.655217+08:00", "timestamp": 1702874640.655217}}}
{"text": "2023-12-18 12:44:07 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023'}\n", "record": {"elapsed": {"repr": "0:00:19.721598", "seconds": 19.721598}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023"}, "file": {"name": "agent.py", "path": "/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 5365, "name": "MainProcess"}, "thread": {"id": 139644727856000, "name": "MainThread"}, "time": {"repr": "2023-12-18 12:44:07.769467+08:00", "timestamp": 1702874647.769467}}}
{"text": "2023-12-18 12:44:42 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023'}\n", "record": {"elapsed": {"repr": "0:00:54.536659", "seconds": 54.536659}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023"}, "file": {"name": "agent.py", "path": "/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 5365, "name": "MainProcess"}, "thread": {"id": 139644727856000, "name": "MainThread"}, "time": {"repr": "2023-12-18 12:44:42.584528+08:00", "timestamp": 1702874682.584528}}}
{"text": "2023-12-18 12:45:19 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023'}\n", "record": {"elapsed": {"repr": "0:01:31.194976", "seconds": 91.194976}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/destiny-2--legacy-collection-2023"}, "file": {"name": "agent.py", "path": "/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 5365, "name": "MainProcess"}, "thread": {"id": 139644727856000, "name": "MainThread"}, "time": {"repr": "2023-12-18 12:45:19.242845+08:00", "timestamp": 1702874719.242845}}}
{"text": "2023-12-18 12:45:55 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (5365), thread 'MainThread' (139644727856000): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/egames4/egames4/epic/src/claim.py\", line 122, in claim_epic_games\n    await epic.claim_weekly_games(page, single_promotions)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 325, in iter\n    raise retry_exc.reraise()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 158, in reraise\n    raise self.last_attempt.result()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/egames4/egames4/epic/src/epic_games/agent.py\", line 320, in claim_weekly_games\n    await page.click(\"//button//span[text()='Check Out']\")\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 10117, in click\n    await self._impl_obj.click(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 694, in click\n    return await self._main_frame.click(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 484, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 62, in send\n    return await self._connection.wrap_api_call(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 492, in wrap_api_call\n    return await cb()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 100, in inner_send\n    result = next(iter(done)).result()\nplaywright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n", "record": {"elapsed": {"repr": "0:02:07.409288", "seconds": 127.409288}, "exception": {"type": "TimeoutError", "value": "Timeout 30000ms exceeded.", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/egames4/egames4/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (5365), thread 'MainThread' (139644727856000):", "module": "claim", "name": "__main__", "process": {"id": 5365, "name": "MainProcess"}, "thread": {"id": 139644727856000, "name": "MainThread"}, "time": {"repr": "2023-12-18 12:45:55.457157+08:00", "timestamp": 1702874755.457157}}}
