2022-10-12 00:59:04.902 | ERROR    | services.deploy:_bad_omen:264 - >> Notify [UnrealClaimer] 推送运行日志 - active_pusher=[] err=認證失敗，可能原因：公网IP被标记为高威胁目标
2022-10-26 01:10:19.285 | ERROR    | services.deploy:_bad_omen:222 - >> Notify [GameClaimer] 推送运行日志 - active_pusher=[] err=Target closed
=========================== logs ===========================
  waiting for frame "xpath=//iframe[contains(@title, 'content of the hCaptcha')]"
  selector resolved to visible <iframe scrolling="no" frameborder="0" title="Main conte…></iframe>
waiting for selector "//iframe[contains(@title, 'content of the hCaptcha')] >> internal:control=enter-frame >> //div[@class='task-image'] >> nth=8"
============================================================
2022-10-26 01:13:39.804 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:698 - >> MISS [CookieManager] Identity token update failed
2022-10-26 01:14:16.094 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (2277), thread 'MainThread' (139914420627264):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 111, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 382, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 75, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 374, in run
    self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/unreal.py", line 75, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 579, in unreal_activate_payment
    offer_buttons.nth(i).click(delay=500)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "//div[@class='asset-list-group']//article//i >> nth=0"
  selector resolved to hidden <i class="add">添加到购物车</i>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not visible - waiting...
============================================================
2022-11-09 00:54:36.537 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1806), thread 'MainThread' (140391680042816):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 404, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 401, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 168, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 155, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 564, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 444, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
2022-12-24 00:36:20.780 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-24 00:36:58.532 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-24 00:36:58.908 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1874), thread 'MainThread' (140518443486272):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 561, in cart_handle_payment
    self._duel_with_challenge(page)  # cart_handle_payment
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 474, in _duel_with_challenge
    resp = self.armor.anti_hcaptcha(page, window=window)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=hedgehog_on_rocks.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
2022-12-24 00:37:00.465 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-24 00:37:31.433 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-24 00:37:31.779 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (2208), thread 'MainThread' (140278969400384):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/unreal.py", line 80, in get_free_content
    self.unreal_handle_payment(page)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 622, in unreal_handle_payment
    self._duel_with_challenge(page)  # unreal
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 474, in _duel_with_challenge
    resp = self.armor.anti_hcaptcha(page, window=window)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=hedgehog_on_rocks.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
2022-12-25 00:34:56.837 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-25 00:35:29.535 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-25 00:35:29.900 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1909), thread 'MainThread' (139759302810688):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 561, in cart_handle_payment
    self._duel_with_challenge(page)  # cart_handle_payment
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 474, in _duel_with_challenge
    resp = self.armor.anti_hcaptcha(page, window=window)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=hedgehog_on_rocks.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
2022-12-25 00:35:31.290 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-25 00:35:58.665 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-25 00:35:58.790 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (2236), thread 'MainThread' (140046527487040):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/unreal.py", line 80, in get_free_content
    self.unreal_handle_payment(page)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 622, in unreal_handle_payment
    self._duel_with_challenge(page)  # unreal
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 474, in _duel_with_challenge
    resp = self.armor.anti_hcaptcha(page, window=window)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=ladybug.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
2022-12-26 00:36:36.433 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (2243), thread 'MainThread' (140034881793088):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 143, in unreal
    Scaffold.claim(silence=silence, ignore=ignore, unreal=True)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 109, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 354, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 348, in run
    result = self.bricklayer.get_free_content(page=context.new_page())
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/unreal.py", line 77, in get_free_content
    self.result = self.unreal_activate_payment(page, init=not i)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 567, in unreal_activate_payment
    page.goto(self.URL_UNREAL_MONTH)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 8114, in goto
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 146, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.unrealengine.com/marketplace/zh-CN/assets?count=20&sortBy=currentPrice&sortDir=ASC&start=0&tag=4910", waiting until "load"
============================================================
2022-12-26 12:08:03.035 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-26 12:08:50.381 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1927), thread 'MainThread' (140524419341376):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 126, in get_free_game
    page.goto(page_link)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 8114, in goto
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 146, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://store.epicgames.com/zh-CN/p/death-stranding", waiting until "load"
============================================================
2022-12-26 12:22:51.832 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1870), thread 'MainThread' (139795743501376):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 126, in get_free_game
    page.goto(page_link)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 8114, in goto
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 146, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://store.epicgames.com/zh-CN/p/death-stranding", waiting until "load"
============================================================
2022-12-30 07:25:45.637 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-30 07:26:16.479 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-30 07:26:16.618 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1966), thread 'MainThread' (140096730811456):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 561, in cart_handle_payment
    self._duel_with_challenge(page)  # cart_handle_payment
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 474, in _duel_with_challenge
    resp = self.armor.anti_hcaptcha(page, window=window)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=ladybug.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
2022-12-31 07:23:46.877 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-31 07:24:20.608 | ERROR    | hcaptcha_challenger._solutions.kernel:request_assets:157 - 0
2022-12-31 07:24:20.979 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1858), thread 'MainThread' (139892169448512):
Traceback (most recent call last):
  File "/home/runner/work/egames4/egames4/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/egames4/egames4/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/egames4/egames4/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/egames4/egames4/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/egames4/egames4/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 561, in cart_handle_payment
    self._duel_with_challenge(page)  # cart_handle_payment
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 474, in _duel_with_challenge
    resp = self.armor.anti_hcaptcha(page, window=window)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 267, in anti_hcaptcha
    self.challenge(frame_challenge, model=model)
  File "/home/runner/work/egames4/egames4/epic/src/services/bricklayer/core.py", line 125, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 63, in solution
    return self.classifier(img_stream, feature_filters=None)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/hcaptcha_challenger/_solutions/resnet.py", line 54, in classifier
    raise ResourceWarning(_err_prompt)  # maybe mercy
ResourceWarning: 
            The remote network does not exist or the local cache has expired.
            1. Check objects.yaml for typos | model=hedgehog_on_rocks.onnx;
            2. Restart the program after deleting the local cache | dir=datas/models/_assets;
            
